HEADER:
  label: "Contacto"

LOCATION:
  embed: "https://googleusercontent.com/maps.google.com/2"

FORM:
  label: "Formulario de Contacto"
  fields:
    - name: "Nombre completo"
    - email: "Correo electr√≥nico"
    - message: "Tu mensaje"
    - submit: "Enviar mensaje"