HEADER:
  label: "Contacto"

USER:
  role: "Desarrollador Python & Web | IA Entusiasta"
  name: "David Vidal Ramírez"
  username: "David650991" # [cite: 1]
  email: "David650991@gmail.com?subject=Contacto%20Profesional%20desde%20Portafolio"
  avatar: "config/assets/avatars/Foto_Infantil_David_Vidal_Ramirez.png"

INFO:
  - label: "Email"
    value: "David650991@gmail.com" # [cite: 1]
    icon: "mail-outline"
  - label: "Teléfono"
    value: "+52 287 124 61 28" # [cite: 1]
    icon: "phone-portrait-outline"
  - label: "Nacimiento"
    value: "15 de Junio, 1991" # Derivado de RFC: VIRD910615 [cite: 12]
    icon: "calendar-outline"
  - label: "Ubicación"
    value: "Tres Valles, Veracruz, MX" # [cite: 1]
    icon: "location-outline"

SOCIAL:
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/in/david-vidal-ramirez-3ba01b147/" # [cite: 1]
  - icon: "logo-github"
    url: "https://github.com/David650991" # [cite: 1]
  - icon: "logo-gitlab"
    url: "https://gitlab.com/david650991" # [cite: 1]